


##1. What is the total revenue generated by male customers?

select gender, sum(purchase_amount_usd) as total_revenue from 
customer_behaviour
group by gender	;

##Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, discount_applied, purchase_amount_usd
from customer_behaviour 
where discount_applied ="Yes" 
AND  purchase_amount_usd >=(select avg(purchase_amount_usd) from customer_behaviour
);

#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as rating
from customer_behaviour
group by item_purchased
order by rating desc
limit 5;


#Q4. Compare the average Purchase Amounts between, Standard and Express Shipping?

select avg(purchase_amount_usd) as avg_purchase_amount, 
         shipping_type
from customer_behaviour
where shipping_type in ("Standard","Express")
group by shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue betweensubscribers and non_subscribers.

Select subscription_status, 
count(customer_id) as total_customers,
avg(purchase_amount_usd) as average_spend,
sum(purchase_amount_usd) as total_revenue
from
customer_behaviour
group by subscription_status;

#Q6. Which 5 products have the highest percentage of puIchases with discounts applied?
select item_purchased as products,
round(
sum( case when discount_applied = "Yes" then 1 else 0 end )*100 / count(*),2) as discount_percentage
from customer_behaviour
group by item_purchased
order by discount_percentage desc
limit 5;


#Q7. Segment customers into New, Returning, and Loyal based on their total number of prevlous purchases, and show the count of each segment.

with customer_type as ( 
select customer_id,previous_purchases,
case when previous_purchases =1 then "New"
when previous_purchases >10  then "Loyal"
else "returning" end as customer_segment
from customer_behaviour)

 select customer_segment, count(*) as no_of_customers
 from   customer_type
 group by customer_segment;


#Q8. What are the top 3 most purchased products within each category?
with no_of_items as (
select  category, item_purchased, count(customer_id) as no_of_orders,	
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_behaviour
group by category, item_purchased)

#select * from no_of_items;
select category, item_purchased, no_of_orders, item_rank 
from no_of_items
where item_rank<=3;
 
